
# Site settings
title: KClog
SEOTitle: Kaiyuan Chen | KClog
header-img: img/post-bg-miui6.jpg
email: chenkaiyuan@ucla.edu
description: "A learner of Artificial Intelligence"
keyword: "陈楷源, KeplerC, Kepler, Machine Learning, AI, Kaiyuan Chen, Kaiyuan Chen, Kaiyuan Chen, Kaiyuan Chen, Chen Kaiyuan"
url: "https://kychen.xyz"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/KeplerC/KeplerC.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "<p>I am <strong>Kaiyuan Chen</strong>, a third-year undergraduate student from University of California, Los Angeles. Now I am working in <a href="http://metro.ucla.edu">Wireless Networking Group (WiNG)</a> at UCLA and my adviser is <a href="http://web.cs.ucla.edu/~yuanjie.li/">Yuanjie Li</a>.</p>
    <p>My general interest is very broad. I study anything related to machine learning, artificial intelligence and big data, especially for anomaly detection and compressed sensing. I am also interested in computer network and bioinformatics. </p> <p>You can find my CV <a href="https://keplerc.github.io/Resume.pdf">here</a></p>"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
#weibo_username:     ckaiyuan
#zhihu_username:     qiubaiying
github_username:    KeplerC
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: kychen

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-109224761-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


